#!/usr/bin/env python3
"""Export browser cookies to a file for yt-dlp.

Usage:
    python export_cookies.py chrome    # Export from Chrome
    python export_cookies.py firefox   # Export from Firefox
    python export_cookies.py edge      # Export from Edge
    python export_cookies.py brave     # Export from Brave
    python export_cookies.py chromium  # Export from Chromium
"""

import sys
from pathlib import Path

try:
    from browser_cookie3 import chrome, firefox, edge, brave, chromium
except ImportError:
    print("Error: browser-cookie3 is required.")
    print("Install it with: pip install browser-cookie3")
    sys.exit(1)

_BROWSERS = {
    "chrome": chrome,
    "firefox": firefox,
    "edge": edge,
    "brave": brave,
    "chromium": chromium,
}


def _get_cookie_file() -> Path:
    """Get the cookie file path from mcptube data directory or current dir."""
    try:
        sys.path.insert(0, str(Path(__file__).parent / "src"))
        from mcptube.config import settings

        cookie_path = settings.data_dir / ".cookies.txt"
        cookie_path.parent.mkdir(parents=True, exist_ok=True)
        return cookie_path
    except Exception:
        pass
    return Path(__file__).parent / ".cookies.txt"


def export_cookies(browser_name: str) -> None:
    """Export cookies from a browser to a Netscape cookie file."""
    browser_name = browser_name.lower()
    if browser_name not in _BROWSERS:
        print(f"Unknown browser: {browser_name}")
        print(f"Supported browsers: {', '.join(_BROWSERS.keys())}")
        sys.exit(1)

    print(f"Exporting cookies from {browser_name}...")
    browser_func = _BROWSERS[browser_name]

    try:
        cookies = browser_func()
    except Exception as e:
        print(f"Error accessing {browser_name} cookies: {e}")
        print("Make sure the browser is installed and you have the required permissions.")
        sys.exit(1)

    cookie_file = _get_cookie_file()
    with open(cookie_file, "w") as f:
        f.write("# Netscape HTTP Cookie File\n")
        f.write("# This file was generated by export_cookies.py\n\n")
        for cookie in cookies:
            # Write in Netscape cookie format
            domain = cookie.domain
            flag = "TRUE" if cookie.domain.startswith(".") else "FALSE"
            path = cookie.path if cookie.path else "/"
            secure = "TRUE" if cookie.secure else "FALSE"
            expiry = int(cookie.expires) if cookie.expires else 0
            name = cookie.name
            value = cookie.value

            f.write(f"{domain}\t{flag}\t{path}\t{secure}\t{expiry}\t{name}\t{value}\n")

    print(f"Cookies exported to: {cookie_file}")
    print("You can now use mcptube to download YouTube videos.")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: python export_cookies.py <browser>")
        print(f"Supported browsers: {', '.join(_BROWSERS.keys())}")
        sys.exit(1)

    export_cookies(sys.argv[1])
